name: Android CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Set Current Date As Env Variable
    - name: Set current date as env variable
      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
    - name: Set repository name as env variable
      run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
   # # Create APK Debug
   #  - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
   #    run: ./gradlew assembleDebug

    # # Create APK Release
    # - name: Build apk release project (APK) - ${{ env.main_project_module }} module
    #   run: ./gradlew assemble

    # # Create Bundle AAB Release
    # # Noted for main module build [main_project_module]:bundleRelease
    # - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
    #   run: ./gradlew bundle

    # # Upload Artifact Build
    #   # Noted For Output [main_project_module]/build/outputs/apk/debug/
    # - name: Upload APK Debug - ${{ env.repository_name }}
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ env.date_today}} - ${{ env.repository_name }} - APK(s) debug generated
    #     path: app/build/outputs/

    - name: Publish Package
      run: ./gradlew publish
      env:
        GPR_USER: ${{ secrets.GPR_USER_ID}}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        
    # - name: Upload app
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: https://maven.pkg.github.com/geoffvargo/android-basics-kotlin-words-app
    #     asset_path: app/build/outputs/apk/debug/app-debug.apk
    #     asset_name: app-debug.apk
    #     content_type: application/vnd.android.package-archive
